dependencies:

  - name: redis
    version: 3.6.5
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: redis.enabled

  - name: postgresql
    version: 0.15.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled

  - name: rabbitmq
    version: 1.1.9
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq.enabled
